### ISSUE TITLE
不知道怎么使用

### ISSUE THREAD

**Issue by ericzzhou** [tangxiangmin/web-skeleton-extension#5]
我安装并运行了该扩展程序，页面上也已经有了变化，但是我不知道怎么把它下载下来。
这是一个尴尬的事情。
我翻看的blog ，依然没有找到方式~

**Comment by tangxiangmin** [comment]
骨架屏的产出是一段HTML代码，只需要将生成的html代码嵌入到应用中就行

这个插件不是很完善，当时只是展示了一种使用Chrome插件生成骨架屏的思路。所以对于最后产出的结果并没有额外做一些处理。

在博客第3章节介绍了将 “将骨架屏嵌入应用”，没记错的话点击生成骨架屏按钮后会在浏览器控制台打印对应根节点的html代码，直接复制出来应该就可以。

**Comment by ericzzhou** [comment]
> 骨架屏的产出是一段HTML代码，只需要将生成的html代码嵌入到应用中就行
> 
> 这个插件不是很完善，当时只是展示了一种使用Chrome插件生成骨架屏的思路。所以对于最后产出的结果并没有额外做一些处理。
> 
> 在博客第3章节介绍了将 “将骨架屏嵌入应用”，没记错的话点击生成骨架屏按钮后会在浏览器控制台打印对应根节点的html代码，直接复制出来应该就可以。

感谢回复，我在 console 里看到的是原始HTML O(∩_∩)O。
另外，不知作者未来会不会继续完善这个插件呢？

**Comment by tangxiangmin** [comment]
这个插件当时只是验证之前的一个想法，其实还有很多需要完善的地方，比如缩小产生的html代码体积、处理vue的scoped css命名等，如果有时间和需求的话可能会继续更新的，感谢你的支持
