### ISSUE TITLE
怎么在chrome内引入插件？

### ISSUE THREAD

**Issue by zhoufanglu** [tangxiangmin/web-skeleton-extension#6]
如题，我把你的项目下载下来了，也运行起来了。
```js
 Compiled successfully.
```
不知道如何使用。

**Comment by tangxiangmin** [comment]
你好，我刚刚补充了readme文件，里面介绍了如何在加载本地Chrome插件，安装完毕之后就可以打开src/index.html目录调试、或者去其他网页验证生成的骨架屏了。

另外这个插件也发布在[应用商店](https://chrome.google.com/webstore/detail/web-skeleton/cnbfholcpekcobijhgkjcmlceomfdpck )了，可以直接安装体验一下

整个插件当时只是为了验证自己的想法，相关的功能都比较简陋，欢迎交流

**Comment by zhoufanglu** [comment]
直接使用console.log的内容吗？ 我复制到html内，好像都错乱了。。

**Comment by tangxiangmin** [comment]
这个插件只是遍历当前页面结构，然后添加特定的样式，将指定的节点渲染成骨架屏的块，所以直接只复制html内容是没有样式的，还依赖原始页面的CSS
